SELECT USER
FROM DUAL;
--==>> TEAM2

-- 관리자테이블 더미데이터 입력
DELETE FROM TBL_ADMIN;
INSERT INTO TBL_ADMIN(ADMIN_ID, ADMIN_PW)
VALUES('ADMIN1', '0001');
--==>> 1 행 이(가) 삽입되었습니다.


SELECT *
FROM TBL_ADMIN;


DELETE FROM TBL_PRO;
-- 교수테이블 더미데이터 입력
INSERT INTO TBL_PRO(PROFESSOR_ID, PROFESSOR_PW, PROFESSOR_NAME, PROFESSOR_SSN, PROFESSOR_JOIN)
VALUES('PRO1' ,'1234567', '김호진', '1234567', SYSDATE);
--==>> 1 행 이(가) 삽입되었습니다.

SELECT *
FROM TBL_PRO;

DELETE FROM TBL_STUDENT;
-- 학생테이블 더미데이터 입력
INSERT INTO TBL_STUDENT(STUDENT_ID, STUDENT_PW, STUDENT_NAME, STUDENT_SSN, STUDENT_JOIN)
VALUES('20220001', '1214423', '최선하', '1214423', SYSDATE);
INSERT INTO TBL_STUDENT(STUDENT_ID, STUDENT_PW, STUDENT_NAME, STUDENT_SSN, STUDENT_JOIN)
VALUES('20220002', '2234567', '임소민', '2234567', SYSDATE);
INSERT INTO TBL_STUDENT(STUDENT_ID, STUDENT_PW, STUDENT_NAME, STUDENT_SSN, STUDENT_JOIN)
VALUES('20220003', '1553767', '오이삭', '1553767', SYSDATE);
INSERT INTO TBL_STUDENT(STUDENT_ID, STUDENT_PW, STUDENT_NAME, STUDENT_SSN, STUDENT_JOIN)
VALUES('20220004', '2655472', '박현지', '2655472', SYSDATE);
--==>> 1 행 이(가) 삽입되었습니다. * 4


SELECT *
FROM TBL_STUDENT;


DELETE FROM TBL_REASON;
-- 탈락사유테이블 더미데이터 입력
INSERT INTO TBL_REASON(REASON_CODE, REASON_DROPOUT)
VALUES('REASON1', '개인사정');
INSERT INTO TBL_REASON(REASON_CODE, REASON_DROPOUT)
VALUES('REASON2', '조기취업');
--==>> 1 행 이(가) 삽입되었습니다. * 2

SELECT *
FROM TBL_REASON;


-- 과목테이블 더미데이터 입력
INSERT INTO TBL_SUBJECT(SUBJECT_CODE, SUBJECT_NAME)
VALUES('S1', 'JAVA');
INSERT INTO TBL_SUBJECT(SUBJECT_CODE, SUBJECT_NAME)
VALUES('S2', 'ORACLE');
INSERT INTO TBL_SUBJECT(SUBJECT_CODE, SUBJECT_NAME)
VALUES('S3', 'HTML');
--==>> 1 행 이(가) 삽입되었습니다. * 3

--DELETE 후 S+번호로 변경
DELETE FROM TBL_SUBJECT;


SELECT *
FROM TBL_SUBJECT;

DELETE FROM TBL_BOOK;
-- 교재테이블 더미데이터 입력
INSERT INTO TBL_BOOK(BOOK_CODE, BOOK_NAME)
VALUES('BOOK1', 'JAVA의 정석');
INSERT INTO TBL_BOOK(BOOK_CODE, BOOK_NAME)
VALUES('BOOK2', '오라클SQL');
--==>> 1 행 이(가) 삽입되었습니다. * 2

SELECT *
FROM TBL_BOOK;

DELETE FROM TBL_COURSE;
-- 과정테이블 더미데이터 입력
INSERT INTO TBL_COURSE(COURSE_CODE, COURSE_NAME)
VALUES('COURSE1', '프론트엔드');
INSERT INTO TBL_COURSE(COURSE_CODE, COURSE_NAME)
VALUES('COURSE2', '백엔드');
INSERT INTO TBL_COURSE(COURSE_CODE, COURSE_NAME)
VALUES('COURSE3', '풀스택');
--==>> 1 행 이(가) 삽입되었습니다. * 3

SELECT *
FROM TBL_COURSE;

DELETE FROM TBL_ROOM;
-- 강의실테이블 더미데이터 입력
INSERT INTO TBL_ROOM(ROOM_CODE, ROOM_NAME)
VALUES('ROOM1', 'F강의장');
INSERT INTO TBL_ROOM(ROOM_CODE, ROOM_NAME)
VALUES('ROOM2', 'G강의장');
--==>> 1 행 이(가) 삽입되었습니다. * 2

SELECT *
FROM TBL_ROOM;

DELETE FROM TBL_COPEN;
-- 과정개설테이블 더미데이터 입력
INSERT INTO TBL_COPEN(COP_CODE, COURSE_CODE, COP_START, COP_END, ROOM_CODE, COP_DATE)
VALUES('COPEN1', 'COURSE1', '2021-12-30', '2022-06-20', 'ROOM1', '2021-11-10');
--==>> 1 행 이(가) 삽입되었습니다.

SELECT *
FROM TBL_COPEN;

DELETE FROM TBL_REGIST;
-- 수강신청테이블 더미데이터 입력
INSERT INTO TBL_REGIST(REGIST_CODE, STUDENT_ID, COP_CODE, REGIST_DATE)
VALUES('REGIST1', '20220001', 'COPEN1', '2021-12-15');
--==>> 1 행 이(가) 삽입되었습니다.

SELECT *
FROM TBL_REGIST;

DELETE FROM TBL_FAIL;
-- 도중탈락테이블 더미데이터 입력
INSERT INTO TBL_FAIL(FAIL_CODE, REGIST_CODE, FAIL_DATE, REASON_CODE)
VALUES('FAIL1', 'REGIST1', '2022-03-01', 'REASON1');
--==>> 1 행 이(가) 삽입되었습니다.

SELECT *
FROM TBL_FAIL;

DELETE FROM TBL_SOPEN;
-- 과목개설테이블 더미데이터 입력
INSERT INTO TBL_SOPEN(SOP_CODE, SUBJECT_CODE, SOP_START, SOP_END, PROFESSOR_ID, COP_CODE
                    , SOP_SILGI, SOP_PILGI, SOP_CHUL, BOOK_CODE, SOP_DATE)
VALUES('SOP1', 'S1', '2022-01-03', '2022-02-27', 'PRO1', 'COPEN1', 40, 40, 20, 'BOOK1', '2021-11-20');
--==>> 1 행 이(가) 삽입되었습니다. 

SELECT *
FROM TBL_SOPEN;

DELETE FROM TBL_GRADE;
-- 성적테이블 더미데이터 입력
INSERT INTO TBL_GRADE(GRADE_CODE, GRADE_SILGI, GRADE_PILGI, GRADE_CHUL, REGIST_CODE, SOP_CODE, GRADE_DATE)
VALUES('GRADE1', 80, 90, 70, 'REGIST1', 'SOP1', '2022-02-28');
--==>> 1 행 이(가) 삽입되었습니다.

SELECT *
FROM TBL_GRADE;


COMMIT;
--==>> 커밋 완료.



-- 더미 데이터 변경 ============================================================
SELECT *
FROM TBL_PRO
WHERE PROFESSOR_ID = 'PRO001';


UPDATE TBL_STUDENT
SET STUDENT_PW = '2655472'
WHERE STUDENT_ID = '20220004';

SELECT *
FROM TBL_STUDENT;


--------------------------------------------------------------------------------

EXEC PRC_STUDENT_INSERT('20220005', '정은정', '2366854');

SELECT * FROM TBL_ADMIN;
SELECT * FROM TBL_STUDENT;
SELECT * FROM TBL_PRO;
SELECT * FROM TBL_FAIL;
SELECT * FROM TBL_REGIST;
SELECT * FROM TBL_COPEN;
SELECT * FROM TBL_ROOM;
SELECT * FROM TBL_COURSE;
SELECT * FROM TBL_BOOK;
SELECT * FROM TBL_SUBJECT;
SELECT * FROM TBL_REASON;
SELECT * FROM TBL_GRADE;
SELECT * FROM TBL_SOPEN;


COMMIT;

/*
DELETE FROM TBL_GRADE;
DELETE FROM TBL_SOPEN;
DELETE FROM TBL_FAIL;
DELETE FROM TBL_REGIST;
DELETE FROM TBL_COPEN;
DELETE FROM TBL_ROOM;
DELETE FROM TBL_COURSE;
DELETE FROM TBL_BOOK;
DELETE FROM TBL_SUBJECT;
DELETE FROM TBL_REASON;
DELETE FROM TBL_PRO;
DELETE FROM TBL_ADMIN;
DELETE FROM TBL_STUDENT;
*/